test:
  clients:
    default:
      database: challenge_test
      hosts:
        - <%= ENV['TEST_DB_HOST'] || 'localhost' %>:27017
      options:
        mode: primary
        connect_timeout: 3
          # In the test environment we lower the retries and retry interval to
          # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    raise_not_found_error: false
